"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { CSSProperties, MouseEvent as ReactMouseEvent } from "react";
import type { GrammarAnnotation, GrammarAnnotationKind, Sentence } from "@/types";
import { grammarActionLabels, grammarPhaseLabels } from "@/lib/grammar-workflow";
import { matchDrawnRange, tokenizeGrammarText } from "@/components/grammar/range-interaction-engine";
import { useRangeTargetPositions } from "@/components/grammar/use-range-target-positions";
import { RangeMarksLayer } from "@/components/grammar/range-marks-layer";
import { InlineRangeBrackets } from "@/components/grammar/inline-range-brackets";

type Point = { x: number; y: number };
const actionAnnotationKind: Partial<Record<string, GrammarAnnotationKind>> = { frame_groups: "group", identify_group_types: "group", identify_word_classes: "word_class", find_nuclei: "nucleus", frame_functions: "function", identify_functions: "function", identify_donors: "donor", identify_receivers: "receiver" };
type Props = { sentence: Sentence; excludedKinds?: GrammarAnnotationKind[]; initialSolvedIds?: string[]; forcedLineBreaks?: number[]; onCompleteChange?: (complete: boolean) => void; finishControl?: React.ReactNode };

export function GrammarExtensionReader({ sentence, excludedKinds = [], initialSolvedIds = [], forcedLineBreaks = [], onCompleteChange, finishControl }: Props) {
  const annotations = useMemo(() => sentence.grammarAnnotations ?? [], [sentence.grammarAnnotations]);
  const steps = useMemo(() => (sentence.workflowPhases ?? []).flatMap((phase) => phase.actions.filter((action) => { const kind = actionAnnotationKind[action.kind]; if (!action.enabled || !kind || excludedKinds.includes(kind)) return false; if (action.kind === "identify_functions" && phase.actions.some((candidate) => candidate.kind === "frame_functions" && candidate.enabled)) return false; return true; }).map((action) => ({ phase, action, kind: actionAnnotationKind[action.kind]! }))), [excludedKinds, sentence.workflowPhases]);
  const [stepIndex, setStepIndex] = useState(0); const [solvedIds, setSolvedIds] = useState<string[]>(initialSolvedIds); const [drawingStart, setDrawingStart] = useState<Point | null>(null); const [drawingCurrent, setDrawingCurrent] = useState<Point | null>(null); const [message, setMessage] = useState("");
  const surfaceRef = useRef<HTMLDivElement>(null); const tokens = useMemo(() => tokenizeGrammarText(sentence.originalText, "extension-token"), [sentence.originalText]);
  const positions = useRangeTargetPositions(surfaceRef, annotations, tokens, "data-extension-token-id");
  const step = steps[stepIndex]; const expected = step ? annotations.filter((annotation) => annotation.kind === step.kind && !solvedIds.includes(annotation.id)) : [];
  const responseMode = step?.action.responseMode ?? (step?.kind === "function" || step?.kind === "group" ? "frame" : "click");
  const complete = stepIndex >= steps.length;

  useEffect(() => { setSolvedIds((current) => Array.from(new Set([...current, ...initialSolvedIds]))); }, [initialSolvedIds]);
  useEffect(() => { if (step && expected.length === 0) setStepIndex((index) => index + 1); }, [expected.length, step]);
  useEffect(() => { onCompleteChange?.(complete); }, [complete, onCompleteChange]);

  function solve(annotation: GrammarAnnotation) { const next = solvedIds.includes(annotation.id) ? solvedIds : [...solvedIds, annotation.id]; setSolvedIds(next); setMessage(annotation.label ? `Oui — ${annotation.label}.` : "Bonne réponse."); if (!annotations.some((candidate) => candidate.kind === step?.kind && !next.includes(candidate.id))) { setStepIndex((index) => index + 1); setDrawingStart(null); setDrawingCurrent(null); } }
  function handleSurfaceClick(event: ReactMouseEvent<HTMLDivElement>) { if (responseMode !== "frame" || !step) return; const surface = surfaceRef.current; if (!surface) return; const rect = surface.getBoundingClientRect(); const point = { x: event.clientX - rect.left, y: event.clientY - rect.top }; if (!drawingStart) { setDrawingStart(point); setDrawingCurrent(point); setMessage("Clique maintenant sur le coin opposé du rectangle."); return; } const left = Math.min(drawingStart.x, point.x) - 7, right = Math.max(drawingStart.x, point.x) + 7, top = Math.min(drawingStart.y, point.y) - 10, bottom = Math.max(drawingStart.y, point.y) + 10; const selected = tokens.filter((token) => { if (!token.isWord) return false; const position = positions[expected.find((annotation) => token.start < annotation.end && token.end > annotation.start)?.id ?? ""]; const element = surface.querySelector<HTMLElement>(`[data-extension-token-id="${token.id}"]`); if (!element) return false; const box = element.getBoundingClientRect(); const x = (box.left + box.right) / 2 - rect.left, y = (box.top + box.bottom) / 2 - rect.top; return Boolean(position) && x >= left && x <= right && y >= top && y <= bottom; }); const start = selected.length ? Math.min(...selected.map((token) => token.start)) : -1, end = selected.length ? Math.max(...selected.map((token) => token.end)) : -1; const match = matchDrawnRange(start, end, expected, [], undefined, Math.max(2, Math.round((end - start) * .28))); setDrawingStart(null); setDrawingCurrent(null); if (match) solve(match); else setMessage("Ce n’est pas tout à fait la bonne partie. Réessaie."); }
  function tokenStyle(start: number, end: number): CSSProperties { const marks = annotations.filter((annotation) => solvedIds.includes(annotation.id) && start < annotation.end && end > annotation.start); const color = [...marks].reverse().find((annotation) => annotation.visualEffect?.kind === "color")?.visualEffect?.color; const backgroundColor = [...marks].reverse().find((annotation) => annotation.visualEffect?.kind === "highlight")?.visualEffect?.color; const underline = [...marks].reverse().find((annotation) => annotation.visualEffect?.kind === "underline")?.visualEffect?.color; return { color, backgroundColor, fontWeight: marks.some((annotation) => annotation.visualEffect?.kind === "bold") ? 800 : undefined, textDecoration: underline ? "underline" : undefined, textDecorationColor: underline }; }
  const bracketTargets = annotations.filter((annotation) => solvedIds.includes(annotation.id) && (annotation.visualEffect?.kind === "brackets" || (!annotation.visualEffect && annotation.kind === "group"))); const frameTargets = annotations.filter((annotation) => solvedIds.includes(annotation.id) && (annotation.visualEffect?.kind === "frame" || (!annotation.visualEffect && annotation.kind === "function")));

  if (!annotations.length) return <>{finishControl}</>;
  return <section className="grammar-extension-reader">
    {!complete && step && <><div className="grammar-reader-progress">{steps.map((item, index) => <span className={index === stepIndex ? "active" : index < stepIndex ? "done" : ""} key={`${item.phase.id}-${item.action.id}`}>{index + 1}</span>)}</div><div className="grammar-reader-instruction"><small>{grammarPhaseLabels[step.phase.kind]}</small><strong>{grammarActionLabels[step.action.kind]}</strong><span>{responseMode === "frame" ? "Clique sur un premier coin, puis sur le coin opposé." : "Clique sur le bon mot."}</span></div></>}
    <div className={`grammar-reader-text shared-grammar-reader-text ${responseMode === "frame" ? "framing" : "clicking"}`} ref={surfaceRef} onClick={handleSurfaceClick} onMouseMove={(event) => { if (!drawingStart || responseMode !== "frame") return; const rect = event.currentTarget.getBoundingClientRect(); setDrawingCurrent({ x: event.clientX - rect.left, y: event.clientY - rect.top }); }}>
      <RangeMarksLayer targets={frameTargets} positions={positions} leftIds={frameTargets.map((target) => target.id)} rightIds={frameTargets.map((target) => target.id)} mode="frame"/>
      {drawingStart && drawingCurrent && <span className="grammar-reader-drawing-frame" style={{ left: Math.min(drawingStart.x, drawingCurrent.x), top: Math.min(drawingStart.y, drawingCurrent.y), width: Math.abs(drawingCurrent.x - drawingStart.x), height: Math.abs(drawingCurrent.y - drawingStart.y) }}/>}{tokens.map((token) => <span key={token.id}>{forcedLineBreaks.some((position) => position >= token.start && position < token.end) && <br/>}{token.isWord ? <button type="button" style={tokenStyle(token.start, token.end)} data-extension-token-id={token.id} onClick={(event) => { if (responseMode !== "click" || !step) return; event.stopPropagation(); const match = expected.find((annotation) => token.start < annotation.end && token.end > annotation.start); if (match) solve(match); else setMessage("Ce n’est pas le bon mot. Réessaie."); }}><InlineRangeBrackets tokenId={token.id} tokenStart={token.start} tokenEnd={token.end} leftTargets={bracketTargets} rightTargets={bracketTargets} keyPrefix="extension-inline"/>{token.text}</button> : <span style={tokenStyle(token.start, token.end)}>{token.text}</span>}</span>)}
    </div>{message && <p className="grammar-reader-message">{message}</p>}{complete && finishControl}
  </section>;
}
