"use client";
import { X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { grammarAnnotationAnswers, grammarAnnotationLabels } from "@/lib/grammar-definitions";
import type { GrammarAnnotationKind, WordClass } from "@/types";

export type GrammarInteractionKind = Exclude<GrammarAnnotationKind, "error">;
export type GrammarResponseMode = "click" | "frame" | "brackets";
export type GrammarInteractionDraft = { kind: GrammarInteractionKind; label: string; instruction: string; responseMode: GrammarResponseMode; nucleusWordClass: WordClass; linkedTargetId: string };
type Props = { open: boolean; draft: GrammarInteractionDraft; functionOptions: string[]; wordClassLabels: Record<WordClass, string>; kinds?: GrammarInteractionKind[]; responseModes?: GrammarResponseMode[]; answerOptions?: Partial<Record<GrammarInteractionKind, string[]>>; linkedTargetLabel?: string; showLinkedTarget?: boolean; onChange: (draft: GrammarInteractionDraft) => void; onCancel: () => void; onSave: () => void; onPickLinkedTarget?: () => void; onClearLinkedTarget?: () => void };

function instruction(kind: GrammarInteractionKind, label: string, mode: GrammarResponseMode) { const target = kind === "nucleus" ? "le noyau du groupe" : label.toLocaleLowerCase("fr-CA"); return mode === "click" ? `Clique sur ${target}.` : mode === "brackets" ? `Mets ${target} entre crochets.` : `Encadre ${target}.`; }
function initialLabel(kind: GrammarInteractionKind, wordClass: WordClass, labels: Record<WordClass, string>, options: Partial<Record<GrammarInteractionKind, string[]>>) { return options[kind]?.[0] ?? (kind === "function" ? "Sujet" : kind === "group" ? "Groupe" : kind === "nucleus" || kind === "word_class" ? labels[wordClass] : grammarAnnotationLabels[kind]); }

export function GrammarInteractionModal({ open, draft, functionOptions, wordClassLabels, kinds = ["function", "group", "nucleus"], responseModes = ["click", "frame"], answerOptions = grammarAnnotationAnswers, linkedTargetLabel, showLinkedTarget = true, onChange, onCancel, onSave, onPickLinkedTarget, onClearLinkedTarget }: Props) {
  if (!open) return null; const choices = draft.kind === "function" ? functionOptions : answerOptions[draft.kind] ?? [];
  return <div className="tree-analysis-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onCancel(); }}><aside className="tree-analysis-inspector tree-analysis-modal" role="dialog" aria-modal="true" aria-label="Créer une réponse interactive">
    <div className="tree-analysis-modal-heading"><div><span className="eyebrow">Réponse interactive</span><h3>Que représente ce passage?</h3></div><button type="button" onClick={onCancel} aria-label="Fermer"><X size={18}/></button></div>
    <label>Type de réponse<select value={draft.kind} onChange={(event) => { const kind = event.target.value as GrammarInteractionKind; const label = initialLabel(kind, draft.nucleusWordClass, wordClassLabels, answerOptions); const responseMode: GrammarResponseMode = kind === "nucleus" || kind === "word_class" ? "click" : responseModes.includes("brackets") ? "brackets" : "frame"; onChange({ ...draft, kind, label, responseMode, linkedTargetId: "", instruction: instruction(kind, label, responseMode) }); }}>{kinds.map((kind) => <option value={kind} key={kind}>{grammarAnnotationLabels[kind]}</option>)}</select></label>
    {draft.kind === "nucleus" ? <label>Classe du noyau<select value={draft.nucleusWordClass} onChange={(event) => { const nucleusWordClass = event.target.value as WordClass; onChange({ ...draft, nucleusWordClass, label: wordClassLabels[nucleusWordClass] }); }}>{(Object.keys(wordClassLabels) as WordClass[]).map((wordClass) => <option value={wordClass} key={wordClass}>{wordClassLabels[wordClass]}</option>)}</select></label> : choices.length > 0 && <label>Réponse attendue<select value={draft.label} onChange={(event) => { const label = event.target.value; onChange({ ...draft, label, instruction: instruction(draft.kind, label, draft.responseMode) }); }}>{choices.map((choice) => <option key={choice}>{choice}</option>)}</select></label>}
    <label>Action de l’élève<select value={draft.responseMode} onChange={(event) => { const responseMode = event.target.value as GrammarResponseMode; onChange({ ...draft, responseMode, instruction: instruction(draft.kind, draft.label, responseMode) }); }}>{responseModes.includes("click") && <option value="click">Cliquer sur le mot ou le passage</option>}{responseModes.includes("frame") && <option value="frame">Tracer un encadrement</option>}{responseModes.includes("brackets") && <option value="brackets">Tracer les crochets</option>}</select></label>
    <label>Consigne affichée<input value={draft.instruction} onChange={(event) => onChange({ ...draft, instruction: event.target.value })}/></label>
    {showLinkedTarget && draft.kind !== "function" && <div className="tree-analysis-linked-node-picker"><span>Rectangle déclenché (facultatif)</span><strong>{linkedTargetLabel ? `Rectangle sélectionné — ${linkedTargetLabel}` : "Aucun rectangle sélectionné"}</strong><div className="tree-analysis-modal-actions">{onPickLinkedTarget && <Button type="button" variant="secondary" onClick={onPickLinkedTarget}>Choisir dans l’arbre</Button>}{draft.linkedTargetId && onClearLinkedTarget && <Button type="button" variant="secondary" onClick={onClearLinkedTarget}>Ne lier aucun rectangle</Button>}</div></div>}
    <p>La marque et le geste sont conservés avec cet évènement et seront rejoués dans le lecteur.</p><div className="tree-analysis-modal-actions"><Button type="button" variant="secondary" onClick={onCancel}>Annuler</Button><Button type="button" onClick={onSave} disabled={!draft.label.trim() || !draft.instruction.trim()}>Créer l’évènement</Button></div>
  </aside></div>;
}
