"use client";

import { useMemo, useRef, useState } from "react";
import { Play, Save, SpellCheck2, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { GrammarWorkflowPlanner } from "@/components/grammar-workflow-planner";
import { GrammarInteractionModal } from "@/components/grammar/grammar-interaction-modal";
import type { GrammarInteractionDraft, GrammarInteractionKind } from "@/components/grammar/grammar-interaction-modal";
import { readTextareaSelection } from "@/components/grammar/shared-textarea-selection";
import { renderSharedAnnotatedText } from "@/components/grammar/shared-annotated-text";
import { createWorkflowPhase } from "@/lib/grammar-workflow";
import { grammarAnnotationAnswers, grammarAnnotationLabels, sentenceFunctionOptions } from "@/lib/grammar-definitions";
import { wordClassLabels } from "@/lib/activity-types";
import { InteractiveSentenceReader } from "@/components/presentation/interactive-sentence-reader";
import type { CorrectionCode, GrammarAnnotation, GrammarPhaseKind, GrammarWorkflowPhase, SchoolLevel, Sentence, SentenceCorrection, SentenceDifficulty } from "@/types";

type Props = { initialSentence?: Sentence; levels: SchoolLevel[]; correctionCodes: CorrectionCode[]; onSave: (sentence: Sentence) => void };
type Selection = { start: number; end: number; text: string };
const phaseByKind: Record<GrammarInteractionKind, GrammarPhaseKind> = { group: "groups", nucleus: "nuclei", function: "functions", word_class: "word_classes", donor: "agreements", receiver: "agreements" };
const visualByKind: Record<GrammarInteractionKind, GrammarAnnotation["visualEffect"]> = { group: { kind: "brackets" }, function: { kind: "brackets" }, nucleus: { kind: "color", color: "#d93434" }, word_class: { kind: "underline", color: "#2467d1" }, donor: { kind: "highlight", color: "#fde68a" }, receiver: { kind: "underline", color: "#22834b" } };

export function MixedActivityEditor({ initialSentence, levels, correctionCodes, onSave }: Props) {
  const textareaRef = useRef<HTMLTextAreaElement>(null); const rememberedSelectionRef = useRef<Selection | null>(null); const now = new Date().toISOString();
  const [title, setTitle] = useState(initialSentence?.title ?? ""); const [levelId, setLevelId] = useState(initialSentence?.levelId ?? levels[0]?.id ?? ""); const [difficulty, setDifficulty] = useState<SentenceDifficulty>(initialSentence?.difficulty ?? "medium"); const [text, setText] = useState(initialSentence?.originalText ?? "");
  const [annotations, setAnnotations] = useState<GrammarAnnotation[]>(initialSentence?.grammarAnnotations ?? []); const [corrections, setCorrections] = useState<SentenceCorrection[]>(initialSentence?.corrections ?? []); const [phases, setPhases] = useState<GrammarWorkflowPhase[]>(initialSentence?.workflowPhases ?? []);
  const [selection, setSelection] = useState<Selection | null>(null); const [draft, setDraft] = useState<GrammarInteractionDraft | null>(null); const [correctionOpen, setCorrectionOpen] = useState(false); const [correctedText, setCorrectedText] = useState(""); const [correctionCodeId, setCorrectionCodeId] = useState(correctionCodes.find((code) => code.isActive !== false)?.id ?? ""); const [showTest, setShowTest] = useState(false); const [message, setMessage] = useState("");
  const sentence = useMemo<Sentence>(() => ({ id: initialSentence?.id ?? "mixed-preview", activityType: "sentence_correction", primaryObjective: "mixed_grammar", title: title.trim() || "Activité mixte", levelId, difficulty, tags: initialSentence?.tags ?? [], originalText: text, corrections, grammarAnnotations: annotations, workflowPhases: phases, assignedGroupIds: initialSentence?.assignedGroupIds ?? [], showCorrectionCount: true, createdAt: initialSentence?.createdAt ?? now, updatedAt: now }), [annotations, corrections, difficulty, initialSentence, levelId, now, phases, text, title]);
  function selected() { const element = textareaRef.current; if (!element) return null; const value = readTextareaSelection(element, text) ?? rememberedSelectionRef.current; if (!value) setMessage("Sélectionne d’abord un mot ou un passage dans la phrase."); else { rememberedSelectionRef.current = value; setSelection(value); setMessage(""); } return value; }
  function ensurePhase(kind: GrammarPhaseKind) { setPhases((current) => current.some((phase) => phase.kind === kind) ? current : [...current, createWorkflowPhase(kind)]); }
  function openAnnotation(kind: GrammarInteractionKind) { const range = selected(); if (!range) return; const label = grammarAnnotationAnswers[kind]?.[0] ?? grammarAnnotationLabels[kind]; const responseMode = kind === "nucleus" || kind === "word_class" ? "click" : "brackets"; setDraft({ kind, label, responseMode, instruction: responseMode === "click" ? `Clique sur ${label.toLowerCase()}.` : `Mets ${label.toLowerCase()} entre crochets.`, nucleusWordClass: "noun", linkedTargetId: "" }); }
  function saveAnnotation() { if (!draft || !selection) return; const label = draft.kind === "group" && draft.label === "GPrép" ? "GPrep" : draft.label; setAnnotations((current) => [...current, { id: crypto.randomUUID(), start: selection.start, end: selection.end, kind: draft.kind, label, responseMode: draft.responseMode, visualEffect: visualByKind[draft.kind] }]); ensurePhase(phaseByKind[draft.kind]); setDraft(null); }
  function saveCorrection() { if (!selection || !correctedText.trim() || !correctionCodeId) return; setCorrections((current) => [...current, { id: crypto.randomUUID(), start: selection.start, end: selection.end, originalText: selection.text, correctedText: correctedText.trim(), correctionCodeId, points: 1, revealOrder: current.length + 1 }]); ensurePhase("correction"); setCorrectionOpen(false); setCorrectedText(""); }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!title.trim() || !text.trim() || !levelId) { setMessage("Le titre, le niveau et la phrase sont obligatoires."); return; } onSave({ ...sentence, id: initialSentence?.id ?? crypto.randomUUID(), title: title.trim(), updatedAt: new Date().toISOString() }); }
  const marks = annotations.map((annotation) => ({ id: annotation.id, start: annotation.start, end: annotation.end, color: annotation.visualEffect?.kind === "color" ? annotation.visualEffect.color : undefined, framed: annotation.visualEffect?.kind === "frame" || annotation.visualEffect?.kind === "brackets", bold: annotation.visualEffect?.kind === "bold" }));

  return <form className="mixed-workspace" onSubmit={submit}>
    <header className="mixed-workspace-meta"><label>Titre<input value={title} onChange={(event) => setTitle(event.target.value)}/></label><label>Niveau<select value={levelId} onChange={(event) => setLevelId(event.target.value)}>{levels.map((level) => <option value={level.id} key={level.id}>{level.name}</option>)}</select></label><label>Difficulté<select value={difficulty} onChange={(event) => setDifficulty(event.target.value as SentenceDifficulty)}><option value="easy">Facile</option><option value="medium">Moyenne</option><option value="hard">Difficile</option></select></label><Button type="button" variant="secondary" onClick={() => setShowTest((value) => !value)}><Play size={17}/>{showTest ? "Fermer le test" : "Tester"}</Button><Button type="submit"><Save size={17}/>Enregistrer</Button></header>
    <div className="mixed-workspace-grid"><main className="mixed-workspace-editor"><div className="mixed-workspace-toolbar" onMouseDown={(event) => event.preventDefault()}><button type="button" onClick={() => { const range = selected(); if (range) { setCorrectedText(""); setCorrectionOpen(true); } }}><SpellCheck2 size={16}/>Erreur</button>{(["group", "nucleus", "function", "word_class", "donor", "receiver"] as GrammarInteractionKind[]).map((kind) => <button type="button" key={kind} onClick={() => openAnnotation(kind)}>{grammarAnnotationLabels[kind]}</button>)}</div>
      <section className="mixed-workspace-surface"><span className="eyebrow">Phrase ou texte de travail</span><textarea ref={textareaRef} rows={8} value={text} onChange={(event) => { setText(event.target.value); rememberedSelectionRef.current = null; }} onSelect={(event) => { const value = readTextareaSelection(event.currentTarget, text); if (value) { rememberedSelectionRef.current = value; setSelection(value); } }} placeholder="Écris ou colle le contenu ici…"/><div className="mixed-workspace-preview">{text ? renderSharedAnnotatedText(text, marks, "tree-analysis-framed-text") : "L’aperçu des réponses apparaîtra ici."}</div></section>
      <section className="mixed-workspace-answers"><h3>Réponses interactives</h3>{corrections.map((correction) => <div key={correction.id}><span>Erreur</span><strong>{correction.originalText} → {correction.correctedText}</strong><button type="button" onClick={() => setCorrections((current) => current.filter((item) => item.id !== correction.id))}><Trash2 size={15}/></button></div>)}{annotations.map((annotation) => <div key={annotation.id}><span>{grammarAnnotationLabels[annotation.kind as GrammarInteractionKind]}</span><strong>{text.slice(annotation.start, annotation.end)} — {annotation.label}</strong><button type="button" onClick={() => setAnnotations((current) => current.filter((item) => item.id !== annotation.id))}><Trash2 size={15}/></button></div>)}</section>{message && <div className="form-message">{message}</div>}</main><aside className="mixed-workspace-phases"><GrammarWorkflowPlanner phases={phases} onChange={setPhases}/></aside></div>
    <GrammarInteractionModal open={Boolean(draft)} draft={draft ?? { kind: "function", label: "Sujet", instruction: "", responseMode: "brackets", nucleusWordClass: "noun", linkedTargetId: "" }} functionOptions={sentenceFunctionOptions} wordClassLabels={wordClassLabels} kinds={["group", "nucleus", "function", "word_class", "donor", "receiver"]} responseModes={["click", "brackets", "frame"]} showLinkedTarget={false} onChange={setDraft} onCancel={() => setDraft(null)} onSave={saveAnnotation}/>
    {correctionOpen && <div className="tree-analysis-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setCorrectionOpen(false); }}><aside className="tree-analysis-inspector tree-analysis-modal"><div className="tree-analysis-modal-heading"><div><span className="eyebrow">Correction</span><h3>« {selection?.text} »</h3></div><button type="button" onClick={() => setCorrectionOpen(false)}><X size={18}/></button></div><label>Correction attendue<input value={correctedText} onChange={(event) => setCorrectedText(event.target.value)} autoFocus/></label><label>Code<select value={correctionCodeId} onChange={(event) => setCorrectionCodeId(event.target.value)}>{correctionCodes.filter((code) => code.isActive !== false).map((code) => <option value={code.id} key={code.id}>{code.code} — {code.name}</option>)}</select></label><div className="tree-analysis-modal-actions"><Button type="button" variant="secondary" onClick={() => setCorrectionOpen(false)}>Annuler</Button><Button type="button" onClick={saveCorrection}>Ajouter l’erreur</Button></div></aside></div>}
    {showTest && <section className="mixed-workspace-test"><div><span className="eyebrow">Test du lecteur</span><h2>Même activité, côté élève</h2></div><InteractiveSentenceReader sentence={sentence} correctionCodes={correctionCodes} onPoint={() => undefined} persistenceKey={`mixed-test-${initialSentence?.id ?? "new"}`} finishControl={<Button type="button" disabled>Terminé</Button>}/></section>}
  </form>;
}
