"use client";

import { useMemo, useRef, useState } from "react";
import { Pencil, Play, Save, SpellCheck2, Trash2, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { GrammarWorkflowPlanner } from "@/components/grammar-workflow-planner";
import { GrammarInteractionModal } from "@/components/grammar/grammar-interaction-modal";
import type { GrammarInteractionDraft, GrammarInteractionKind } from "@/components/grammar/grammar-interaction-modal";
import { captureSharedTextSelection, rebaseSharedTextRange, renderSharedAnnotatedText } from "@/components/grammar/shared-annotated-text";
import { createWorkflowPhase } from "@/lib/grammar-workflow";
import { grammarAnnotationAnswers, grammarAnnotationLabels, sentenceFunctionOptions } from "@/lib/grammar-definitions";
import { wordClassLabels } from "@/lib/activity-types";
import { InteractiveSentenceReader } from "@/components/presentation/interactive-sentence-reader";
import type { CorrectionCode, GrammarAnnotation, GrammarPhaseKind, GrammarWorkflowPhase, SchoolLevel, Sentence, SentenceCorrection, SentenceDifficulty } from "@/types";

type Props = { initialSentence?: Sentence; levels: SchoolLevel[]; correctionCodes: CorrectionCode[]; onSave: (sentence: Sentence) => void };
type Selection = { start: number; end: number; text: string };
const phaseByKind: Record<GrammarInteractionKind, GrammarPhaseKind> = { group: "groups", nucleus: "nuclei", function: "functions", word_class: "word_classes", donor: "agreements", receiver: "agreements" };
const visualByKind: Record<GrammarInteractionKind, GrammarAnnotation["visualEffect"]> = { group: { kind: "brackets" }, function: { kind: "brackets" }, nucleus: { kind: "color", color: "#d93434" }, word_class: { kind: "underline", color: "#2467d1" }, donor: { kind: "highlight", color: "#fde68a" }, receiver: { kind: "underline", color: "#22834b" } };

export function MixedActivityEditor({ initialSentence, levels, correctionCodes, onSave }: Props) {
  const surfaceRef = useRef<HTMLDivElement>(null); const rememberedSelectionRef = useRef<Selection | null>(null); const now = new Date().toISOString();
  const [title, setTitle] = useState(initialSentence?.title ?? ""); const [levelId, setLevelId] = useState(initialSentence?.levelId ?? levels[0]?.id ?? ""); const [difficulty, setDifficulty] = useState<SentenceDifficulty>(initialSentence?.difficulty ?? "medium"); const [text, setText] = useState(initialSentence?.originalText ?? "");
  const [annotations, setAnnotations] = useState<GrammarAnnotation[]>(initialSentence?.grammarAnnotations ?? []); const [corrections, setCorrections] = useState<SentenceCorrection[]>(initialSentence?.corrections ?? []); const [phases, setPhases] = useState<GrammarWorkflowPhase[]>(initialSentence?.workflowPhases ?? []);
  const [selection, setSelection] = useState<Selection | null>(null); const [draft, setDraft] = useState<GrammarInteractionDraft | null>(null); const [editingAnnotationId, setEditingAnnotationId] = useState<string | null>(null); const [correctionOpen, setCorrectionOpen] = useState(false); const [correctedText, setCorrectedText] = useState(""); const [correctionCodeId, setCorrectionCodeId] = useState(correctionCodes.find((code) => code.isActive !== false)?.id ?? ""); const [showTest, setShowTest] = useState(false); const [message, setMessage] = useState("");
  const sentence = useMemo<Sentence>(() => ({ id: initialSentence?.id ?? "mixed-preview", activityType: "sentence_correction", primaryObjective: "mixed_grammar", title: title.trim() || "Activité mixte", levelId, difficulty, tags: initialSentence?.tags ?? [], originalText: text, corrections, grammarAnnotations: annotations, workflowPhases: phases, assignedGroupIds: initialSentence?.assignedGroupIds ?? [], showCorrectionCount: true, createdAt: initialSentence?.createdAt ?? now, updatedAt: now }), [annotations, corrections, difficulty, initialSentence, levelId, now, phases, text, title]);
  function captureSelection() { const element = surfaceRef.current; const range = element ? captureSharedTextSelection(element) : null; if (!range || range.start === range.end) return rememberedSelectionRef.current; let start = Math.min(range.start, range.end); let end = Math.max(range.start, range.end); while (start < end && /\s/.test(text[start] ?? "")) start += 1; while (end > start && /\s/.test(text[end - 1] ?? "")) end -= 1; if (start === end) return rememberedSelectionRef.current; const value = { start, end, text: text.slice(start, end) }; rememberedSelectionRef.current = value; setSelection(value); return value; }
  function selected() { const value = captureSelection(); if (!value) setMessage("Sélectionne d’abord un mot ou un passage dans la phrase."); else setMessage(""); return value; }
  function updateText(nextText: string) { if (nextText === text) return; setAnnotations((current) => current.map((annotation) => ({ ...annotation, ...rebaseSharedTextRange(text, nextText, annotation.start, annotation.end) })).filter((annotation) => annotation.start < annotation.end)); setCorrections((current) => current.map((correction) => { const range = rebaseSharedTextRange(text, nextText, correction.start, correction.end); return { ...correction, ...range, originalText: nextText.slice(range.start, range.end) }; }).filter((correction) => correction.start < correction.end)); setText(nextText); rememberedSelectionRef.current = null; setSelection(null); }
  function ensurePhase(kind: GrammarPhaseKind) { setPhases((current) => current.some((phase) => phase.kind === kind) ? current : [...current, createWorkflowPhase(kind)]); }
  function openAnnotation(kind: GrammarInteractionKind) { const range = selected(); if (!range) return; setEditingAnnotationId(null); const label = grammarAnnotationAnswers[kind]?.[0] ?? grammarAnnotationLabels[kind]; const responseMode = kind === "nucleus" || kind === "word_class" ? "click" : "brackets"; setDraft({ kind, label, responseMode, instruction: responseMode === "click" ? `Clique sur ${label.toLowerCase()}.` : `Mets ${label.toLowerCase()} entre crochets.`, nucleusWordClass: "noun", linkedTargetId: "", visualEffect: visualByKind[kind] }); }
  function editAnnotation(annotation: GrammarAnnotation) { const range = { start: annotation.start, end: annotation.end, text: text.slice(annotation.start, annotation.end) }; setSelection(range); rememberedSelectionRef.current = range; setEditingAnnotationId(annotation.id); setDraft({ kind: annotation.kind as GrammarInteractionKind, label: annotation.label ?? grammarAnnotationLabels[annotation.kind as GrammarInteractionKind], responseMode: annotation.responseMode ?? "click", instruction: annotation.responseMode === "brackets" ? `Mets ${(annotation.label ?? "ce passage").toLowerCase()} entre crochets.` : annotation.responseMode === "frame" ? `Encadre ${(annotation.label ?? "ce passage").toLowerCase()}.` : `Clique sur ${(annotation.label ?? "ce passage").toLowerCase()}.`, nucleusWordClass: "noun", linkedTargetId: "", visualEffect: annotation.visualEffect, parentAnnotationId: annotation.parentAnnotationId }); }
  function saveAnnotation() { if (!draft || !selection) return; const label = draft.kind === "group" && draft.label === "GPrép" ? "GPrep" : draft.label; const annotation: GrammarAnnotation = { id: editingAnnotationId ?? crypto.randomUUID(), start: selection.start, end: selection.end, kind: draft.kind, label, responseMode: draft.responseMode, visualEffect: draft.visualEffect ?? visualByKind[draft.kind], parentAnnotationId: draft.parentAnnotationId }; setAnnotations((current) => editingAnnotationId ? current.map((item) => item.id === editingAnnotationId ? annotation : item) : [...current, annotation]); ensurePhase(phaseByKind[draft.kind]); setDraft(null); setEditingAnnotationId(null); }
  function saveCorrection() { if (!selection || !correctedText.trim() || !correctionCodeId) return; setCorrections((current) => [...current, { id: crypto.randomUUID(), start: selection.start, end: selection.end, originalText: selection.text, correctedText: correctedText.trim(), correctionCodeId, points: 1, revealOrder: current.length + 1 }]); ensurePhase("correction"); setCorrectionOpen(false); setCorrectedText(""); }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!title.trim() || !text.trim() || !levelId) { setMessage("Le titre, le niveau et la phrase sont obligatoires."); return; } onSave({ ...sentence, id: initialSentence?.id ?? crypto.randomUUID(), title: title.trim(), updatedAt: new Date().toISOString() }); }
  const marks = annotations.map((annotation) => ({ id: annotation.id, start: annotation.start, end: annotation.end, color: annotation.visualEffect?.kind === "color" ? annotation.visualEffect.color : undefined, backgroundColor: annotation.visualEffect?.kind === "highlight" ? annotation.visualEffect.color : undefined, underlineColor: annotation.visualEffect?.kind === "underline" ? annotation.visualEffect.color : undefined, framed: annotation.visualEffect?.kind === "frame" || annotation.visualEffect?.kind === "brackets" ? true : undefined, bold: annotation.visualEffect?.kind === "bold" ? true : undefined }));
  const parentOptions = annotations.map((annotation) => ({ id: annotation.id, label: `${grammarAnnotationLabels[annotation.kind as GrammarInteractionKind]} — ${text.slice(annotation.start, annotation.end)}` }));

  return <form className="mixed-workspace" onSubmit={submit}>
    <header className="mixed-workspace-meta"><label>Titre<input value={title} onChange={(event) => setTitle(event.target.value)}/></label><label>Niveau<select value={levelId} onChange={(event) => setLevelId(event.target.value)}>{levels.map((level) => <option value={level.id} key={level.id}>{level.name}</option>)}</select></label><label>Difficulté<select value={difficulty} onChange={(event) => setDifficulty(event.target.value as SentenceDifficulty)}><option value="easy">Facile</option><option value="medium">Moyenne</option><option value="hard">Difficile</option></select></label><Button type="button" variant="secondary" onClick={() => setShowTest((value) => !value)}><Play size={17}/>{showTest ? "Fermer le test" : "Tester"}</Button><Button type="submit"><Save size={17}/>Enregistrer</Button></header>
    <div className="mixed-workspace-grid"><main className="mixed-workspace-editor"><div className="mixed-workspace-toolbar" onMouseDown={(event) => event.preventDefault()}><button type="button" onClick={() => { const range = selected(); if (range) { setCorrectedText(""); setCorrectionOpen(true); } }}><SpellCheck2 size={16}/>Erreur</button>{(["group", "nucleus", "function", "word_class", "donor", "receiver"] as GrammarInteractionKind[]).map((kind) => <button type="button" key={kind} onClick={() => openAnnotation(kind)}>{grammarAnnotationLabels[kind]}</button>)}</div>
      <section className="mixed-workspace-surface"><span className="eyebrow">Phrase ou texte de travail</span><div ref={surfaceRef} className="mixed-workspace-editable" contentEditable suppressContentEditableWarning spellCheck onMouseUp={captureSelection} onKeyUp={captureSelection} onInput={(event) => updateText(event.currentTarget.innerText.replace(/\r/g, ""))} data-placeholder="Écris ou colle le contenu ici…">{renderSharedAnnotatedText(text, marks, "tree-analysis-framed-text")}</div><small>Sélectionne directement un passage, puis choisis sa mécanique dans la barre. Les réponses restent visibles dans cette même zone.</small></section>
      <section className="mixed-workspace-answers"><h3>Réponses interactives</h3>{corrections.map((correction) => <div key={correction.id}><span>Erreur</span><strong>{correction.originalText} → {correction.correctedText}</strong><span className="mixed-answer-actions"><button type="button" onClick={() => setCorrections((current) => current.filter((item) => item.id !== correction.id))}><Trash2 size={15}/></button></span></div>)}{annotations.map((annotation) => <div key={annotation.id} className={annotation.parentAnnotationId ? "is-child" : undefined}><span>{grammarAnnotationLabels[annotation.kind as GrammarInteractionKind]}</span><strong>{text.slice(annotation.start, annotation.end)} — {annotation.label}{annotation.parentAnnotationId && <small>Après : {annotations.find((item) => item.id === annotation.parentAnnotationId)?.label}</small>}</strong><span className="mixed-answer-actions"><button type="button" aria-label="Modifier" onClick={() => editAnnotation(annotation)}><Pencil size={15}/></button><button type="button" aria-label="Supprimer" onClick={() => setAnnotations((current) => current.filter((item) => item.id !== annotation.id).map((item) => item.parentAnnotationId === annotation.id ? { ...item, parentAnnotationId: undefined } : item))}><Trash2 size={15}/></button></span></div>)}</section>{message && <div className="form-message">{message}</div>}</main><aside className="mixed-workspace-phases"><GrammarWorkflowPlanner phases={phases} onChange={setPhases}/></aside></div>
    <GrammarInteractionModal open={Boolean(draft)} draft={draft ?? { kind: "function", label: "Sujet", instruction: "", responseMode: "brackets", nucleusWordClass: "noun", linkedTargetId: "", visualEffect: { kind: "brackets" } }} functionOptions={sentenceFunctionOptions} wordClassLabels={wordClassLabels} kinds={["group", "nucleus", "function", "word_class", "donor", "receiver"]} responseModes={["click", "brackets", "frame"]} showLinkedTarget={false} configureVisual parentOptions={parentOptions} onChange={setDraft} onCancel={() => setDraft(null)} onSave={saveAnnotation}/>
    {correctionOpen && <div className="tree-analysis-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setCorrectionOpen(false); }}><aside className="tree-analysis-inspector tree-analysis-modal"><div className="tree-analysis-modal-heading"><div><span className="eyebrow">Correction</span><h3>« {selection?.text} »</h3></div><button type="button" onClick={() => setCorrectionOpen(false)}><X size={18}/></button></div><label>Correction attendue<input value={correctedText} onChange={(event) => setCorrectedText(event.target.value)} autoFocus/></label><label>Code<select value={correctionCodeId} onChange={(event) => setCorrectionCodeId(event.target.value)}>{correctionCodes.filter((code) => code.isActive !== false).map((code) => <option value={code.id} key={code.id}>{code.code} — {code.name}</option>)}</select></label><div className="tree-analysis-modal-actions"><Button type="button" variant="secondary" onClick={() => setCorrectionOpen(false)}>Annuler</Button><Button type="button" onClick={saveCorrection}>Ajouter l’erreur</Button></div></aside></div>}
    {showTest && <section className="mixed-workspace-test"><div><span className="eyebrow">Test du lecteur</span><h2>Même activité, côté élève</h2></div><InteractiveSentenceReader sentence={sentence} correctionCodes={correctionCodes} onPoint={() => undefined} persistenceKey={`mixed-test-${initialSentence?.id ?? "new"}`} finishControl={<Button type="button" disabled>Terminé</Button>}/></section>}
  </form>;
}
